name: ci
permissions:
  contents: read
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile
        run: make build

  examples:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
                
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: make build

      - name: Run examples
        run: make examples
        env:
          DEEPGRAM_API_KEY: ${{ secrets.DG_TOKEN }}
          DEEPGRAM_PROJECT_ID: ${{ secrets.DG_PROJECT_ID }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
                
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: make test

      - name: Test ESM
        run: make test-esm

  test-browser:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
                
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: make build

      - name: Run browser tests
        run: make browser
        env:
          DEEPGRAM_API_KEY: ${{ secrets.DG_TOKEN }}
          DEEPGRAM_PROJECT_ID: ${{ secrets.DG_PROJECT_ID }}
